//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureDisplay.BLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int ID { get; set; }
        public string ImageName { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> opinion { get; set; }
        public string user { get; set; }
    }
}
